language: d

os:
  - linux
  - osx

d:
  - dmd
  - gdc
  - ldc

addons:
  apt:
    packages:
    - gcc-multilib

env:
  - ARCH=x86_64
  - ARCH=x86

script:
  - dub test --arch=$ARCH

branches:
  only:
    - master

notifications:
  email: true

sudo: false

matrix:
  allow_failures:
    - os: osx
      d: gdc # not installed on travis
    - os: osx
      env: ARCH=x86 # not supported
